# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/COJT/tutorial/Synth/adder.cache/wt [current_project]
set_property parent.project_path C:/COJT/tutorial/Synth/adder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property ip_output_repo c:/COJT/tutorial/Synth/adder.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/COJT/tutorial/RTL/half_adder.v
  C:/COJT/tutorial/RTL/full_adder.v
  C:/COJT/tutorial/RTL/ripple_adder.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top ripple_adder -part xc7z020clg484-1


write_checkpoint -force -noxdef ripple_adder.dcp

catch { report_utilization -file ripple_adder_utilization_synth.rpt -pb ripple_adder_utilization_synth.pb }
